spring.application.name=cocos-forest

spring.datasource.url=jdbc:mysql://cocos-forest-db:3306/cocos_forest?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=coco1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update