import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#DCFCE7" },
  board: { flex: 1 },

  infoBar: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  infoBlock: { gap: 4, flex: 1 },
  infoLabel: { fontSize: 13, color: "#6b7280", fontWeight: "600" },
  infoValue: { fontSize: 18, color: "#CA8A04", fontWeight: "700" },
  growthValue: { color: "#15803D" },
  infoDivider: {
    width: 1,
    height: 24,
    backgroundColor: "#e5e7eb",
    marginHorizontal: 12,
  },

  cocoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 8,
    gap: 10,
  },
  cocoBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  cocoImg: { width: 44, height: 44, resizeMode: "contain" },
  bubbleWrap: { position: "relative", flexShrink: 1 },
  bubble: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    maxWidth: 260,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  bubbleText: { color: "#111827", fontSize: 13, lineHeight: 18 },
  bubbleTail: {
    position: "absolute",
    left: -6,
    top: 16,
    width: 12,
    height: 12,
    backgroundColor: "#ffffff",
    transform: [{ rotate: "45deg" }],
  },

  fab: {
    position: "absolute",
    right: 16,
    bottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 9999,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  fabText: { color: "#fff", fontWeight: "700", fontSize: 12 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCard: {
    width: 300,
    padding: 16,
    borderRadius: 12,
    backgroundColor: "#1e1f24",
    gap: 10,
  },
  modalTitle: { fontSize: 18, fontWeight: "700", color: "#fff" },
  modalText: { fontSize: 16, color: "#dcdcdc" },
  modalHint: { fontSize: 15, color: "#a8e6cf" },
  modalBtn: {
    marginTop: 8,
    backgroundColor: "#3b82f6",
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  modalBtnText: { color: "#fff", fontWeight: "700" },
});
